# BitBucket Pipeline para fazer a integração contínua com Git e Deploy em Google Cloud App Engine Standard

image: node:8.10.0

pipelines:
  branches:
    master:
      - step:
          name: Rodando a build (CI=true)
          deployment: test
          caches:
            - node
          script:
            - npm install
            - npm run build
      - step:
          name: Fazendo testes
          deployment: staging
          script:
            - npm install
            - npm run test
      - step:
          name: Enviando para o App Engine Std
          deployment: production
          script:
            - npm install
            - npm run build
            - pipe: atlassian/google-app-engine-deploy:0.2.1
              variables:
                KEY_FILE: $KEY_FILE
                PROJECT: 'nexa-digital'
                VERSION: 'flex'
                PROMOTE: 'true'